require: rubocop-rails

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'test/**/*'
    - 'app/channels/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config.ru'
    - 'db/migrate/**/*'
    - 'db/data/**/*'
    - 'app/views/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Rails/Output:
  Exclude:
    - 'db/add_categories.rb'

Style/ClassVars:
  Enabled: false
